"""Seed script para inserir 20 carros na tabela `carros`.

Observações:
- Este arquivo NÃO executa inserções ao ser importado; rode-o diretamente:
    python scripts/seed_carros.py
- Revise `DATABASE_URL` em `.env` antes de executar para evitar inserir em um banco errado.
"""

# Quando este script é executado diretamente (python scripts/seed_carros.py)
# o import "app" pode falhar porque o diretório do projeto pode não estar
# no sys.path. Aqui garantimos que o diretório raiz do projeto (pai de
# `scripts/`) seja adicionado ao sys.path para que imports como
# `from app...` funcionem.
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from decimal import Decimal
from datetime import datetime
from app.core.database import SessionLocal, engine, Base
from app.models.carro_model import Carro


CARROS = [
    {
        "nome": "Corolla XEi",
        "marca": "Toyota",
        "modelo": "XEi",
        "ano_fabricacao": 2018,
        "ano_modelo": 2019,
        "tipo": "Sedan",
        "descricao": "Sedan confortável, bem conservado",
        "cor": "Prata",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.8",
        "potencia": "139 hp",
        "quilometragem": 45000,
        "preco": Decimal("85000.00"),
        "portas": 4,
        "placa": "AAA1A01",
        "renavam": "00000000001",
        "status": "Disponível",
    },
    {
        "nome": "Civic EX",
        "marca": "Honda",
        "modelo": "EX",
        "ano_fabricacao": 2017,
        "ano_modelo": 2018,
        "tipo": "Sedan",
        "descricao": "Único dono, interior em ótimo estado",
        "cor": "Preto",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "2.0",
        "potencia": "155 hp",
        "quilometragem": 60000,
        "preco": Decimal("78000.00"),
        "portas": 4,
        "placa": "AAA1A02",
        "renavam": "00000000002",
        "status": "Disponível",
    },
    {
        "nome": "Ka SE",
        "marca": "Ford",
        "modelo": "SE",
        "ano_fabricacao": 2016,
        "ano_modelo": 2016,
        "tipo": "Hatchback",
        "descricao": "Econômico e ágil para cidade",
        "cor": "Branco",
        "combustivel": "Flex",
        "cambio": "Manual",
        "motor": "1.0",
        "potencia": "80 hp",
        "quilometragem": 85000,
        "preco": Decimal("35000.00"),
        "portas": 4,
        "placa": "AAA1A03",
        "renavam": "00000000003",
        "status": "Disponível",
    },
    {
        "nome": "Onix LT",
        "marca": "Chevrolet",
        "modelo": "LT",
        "ano_fabricacao": 2019,
        "ano_modelo": 2019,
        "tipo": "Hatchback",
        "descricao": "Baixa quilometragem, completo",
        "cor": "Vermelho",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.4",
        "potencia": "106 hp",
        "quilometragem": 30000,
        "preco": Decimal("62000.00"),
        "portas": 4,
        "placa": "AAA1A04",
        "renavam": "00000000004",
        "status": "Disponível",
    },
    {
        "nome": "Golf GTI",
        "marca": "Volkswagen",
        "modelo": "GTI",
        "ano_fabricacao": 2015,
        "ano_modelo": 2015,
        "tipo": "Hatchback",
        "descricao": "Versão esportiva, motor potente",
        "cor": "Azul",
        "combustivel": "Gasolina",
        "cambio": "Manual",
        "motor": "2.0 Turbo",
        "potencia": "220 hp",
        "quilometragem": 90000,
        "preco": Decimal("92000.00"),
        "portas": 2,
        "placa": "AAA1A05",
        "renavam": "00000000005",
        "status": "Disponível",
    },
    {
        "nome": "X1 20i",
        "marca": "BMW",
        "modelo": "X1",
        "ano_fabricacao": 2018,
        "ano_modelo": 2019,
        "tipo": "SUV",
        "descricao": "SUV compacto premium",
        "cor": "Cinza",
        "combustivel": "Gasolina",
        "cambio": "Automático",
        "motor": "2.0",
        "potencia": "192 hp",
        "quilometragem": 55000,
        "preco": Decimal("150000.00"),
        "portas": 4,
        "placa": "AAA1A06",
        "renavam": "00000000006",
        "status": "Disponível",
    },
    {
        "nome": "C200",
        "marca": "Mercedes",
        "modelo": "C200",
        "ano_fabricacao": 2017,
        "ano_modelo": 2018,
        "tipo": "Sedan",
        "descricao": "Sedan executivo, muito confortável",
        "cor": "Preto",
        "combustivel": "Gasolina",
        "cambio": "Automático",
        "motor": "2.0",
        "potencia": "184 hp",
        "quilometragem": 70000,
        "preco": Decimal("170000.00"),
        "portas": 4,
        "placa": "AAA1A07",
        "renavam": "00000000007",
        "status": "Disponível",
    },
    {
        "nome": "A3 Sedan",
        "marca": "Audi",
        "modelo": "A3",
        "ano_fabricacao": 2016,
        "ano_modelo": 2016,
        "tipo": "Sedan",
        "descricao": "Boa dirigibilidade e acabamento",
        "cor": "Branco",
        "combustivel": "Gasolina",
        "cambio": "Automático",
        "motor": "1.8",
        "potencia": "170 hp",
        "quilometragem": 80000,
        "preco": Decimal("98000.00"),
        "portas": 4,
        "placa": "AAA1A08",
        "renavam": "00000000008",
        "status": "Disponível",
    },
    {
        "nome": "HB20 Comfort",
        "marca": "Hyundai",
        "modelo": "HB20",
        "ano_fabricacao": 2020,
        "ano_modelo": 2020,
        "tipo": "Hatchback",
        "descricao": "Novo, revisão em dia",
        "cor": "Prata",
        "combustivel": "Flex",
        "cambio": "Manual",
        "motor": "1.0",
        "potencia": "80 hp",
        "quilometragem": 15000,
        "preco": Decimal("68000.00"),
        "portas": 4,
        "placa": "AAA1A09",
        "renavam": "00000000009",
        "status": "Disponível",
    },
    {
        "nome": "Sentra SV",
        "marca": "Nissan",
        "modelo": "Sentra",
        "ano_fabricacao": 2015,
        "ano_modelo": 2015,
        "tipo": "Sedan",
        "descricao": "Ótima estabilidade e consumo",
        "cor": "Azul",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "2.0",
        "potencia": "140 hp",
        "quilometragem": 90000,
        "preco": Decimal("42000.00"),
        "portas": 4,
        "placa": "AAA1A10",
        "renavam": "00000000010",
        "status": "Disponível",
    },
    {
        "nome": "Sportage LX",
        "marca": "Kia",
        "modelo": "Sportage",
        "ano_fabricacao": 2018,
        "ano_modelo": 2018,
        "tipo": "SUV",
        "descricao": "Espaçoso e confortável",
        "cor": "Branco",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "2.0",
        "potencia": "167 hp",
        "quilometragem": 65000,
        "preco": Decimal("110000.00"),
        "portas": 4,
        "placa": "AAA1A11",
        "renavam": "00000000011",
        "status": "Disponível",
    },
    {
        "nome": "Sandero Auth",
        "marca": "Renault",
        "modelo": "Sandero",
        "ano_fabricacao": 2014,
        "ano_modelo": 2014,
        "tipo": "Hatchback",
        "descricao": "Custo-benefício excelente",
        "cor": "Cinza",
        "combustivel": "Flex",
        "cambio": "Manual",
        "motor": "1.0",
        "potencia": "75 hp",
        "quilometragem": 120000,
        "preco": Decimal("26000.00"),
        "portas": 4,
        "placa": "AAA1A12",
        "renavam": "00000000012",
        "status": "Disponível",
    },
    {
        "nome": "208 Active",
        "marca": "Peugeot",
        "modelo": "208",
        "ano_fabricacao": 2019,
        "ano_modelo": 2019,
        "tipo": "Hatchback",
        "descricao": "Compacto com bom acabamento",
        "cor": "Vermelho",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.6",
        "potencia": "118 hp",
        "quilometragem": 40000,
        "preco": Decimal("54000.00"),
        "portas": 4,
        "placa": "AAA1A13",
        "renavam": "00000000013",
        "status": "Disponível",
    },
    {
        "nome": "Toro Freedom",
        "marca": "Fiat",
        "modelo": "Toro",
        "ano_fabricacao": 2020,
        "ano_modelo": 2020,
        "tipo": "Pickup",
        "descricao": "Versátil para família e trabalho",
        "cor": "Prata",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.8",
        "potencia": "139 hp",
        "quilometragem": 35000,
        "preco": Decimal("125000.00"),
        "portas": 4,
        "placa": "AAA1A14",
        "renavam": "00000000014",
        "status": "Disponível",
    },
    {
        "nome": "Impreza 2.0",
        "marca": "Subaru",
        "modelo": "Impreza",
        "ano_fabricacao": 2016,
        "ano_modelo": 2016,
        "tipo": "Hatchback",
        "descricao": "Tração 4x4, robusto",
        "cor": "Azul",
        "combustivel": "Gasolina",
        "cambio": "Manual",
        "motor": "2.0",
        "potencia": "150 hp",
        "quilometragem": 110000,
        "preco": Decimal("68000.00"),
        "portas": 4,
        "placa": "AAA1A15",
        "renavam": "00000000015",
        "status": "Disponível",
    },
    {
        "nome": "Lancer HL",
        "marca": "Mitsubishi",
        "modelo": "Lancer",
        "ano_fabricacao": 2013,
        "ano_modelo": 2013,
        "tipo": "Sedan",
        "descricao": "Durável e confiável",
        "cor": "Prata",
        "combustivel": "Gasolina",
        "cambio": "Manual",
        "motor": "2.0",
        "potencia": "140 hp",
        "quilometragem": 140000,
        "preco": Decimal("32000.00"),
        "portas": 4,
        "placa": "AAA1A16",
        "renavam": "00000000016",
        "status": "Disponível",
    },
    {
        "nome": "Mazda 3",
        "marca": "Mazda",
        "modelo": "3",
        "ano_fabricacao": 2018,
        "ano_modelo": 2018,
        "tipo": "Sedan",
        "descricao": "Boa dirigibilidade e economia",
        "cor": "Branco",
        "combustivel": "Gasolina",
        "cambio": "Automático",
        "motor": "2.0",
        "potencia": "155 hp",
        "quilometragem": 50000,
        "preco": Decimal("92000.00"),
        "portas": 4,
        "placa": "AAA1A17",
        "renavam": "00000000017",
        "status": "Disponível",
    },
    {
        "nome": "NX 300h",
        "marca": "Lexus",
        "modelo": "NX",
        "ano_fabricacao": 2019,
        "ano_modelo": 2019,
        "tipo": "SUV",
        "descricao": "Híbrido premium, silencioso",
        "cor": "Preto",
        "combustivel": "Híbrido",
        "cambio": "Automático",
        "motor": "2.0",
        "potencia": "194 hp",
        "quilometragem": 40000,
        "preco": Decimal("210000.00"),
        "portas": 4,
        "placa": "AAA1A18",
        "renavam": "00000000018",
        "status": "Disponível",
    },
    {
        "nome": "V60",
        "marca": "Volvo",
        "modelo": "V60",
        "ano_fabricacao": 2017,
        "ano_modelo": 2017,
        "tipo": "Station",
        "descricao": "Seguro e espaçoso",
        "cor": "Cinza",
        "combustivel": "Diesel",
        "cambio": "Automático",
        "motor": "2.0",
        "potencia": "190 hp",
        "quilometragem": 85000,
        "preco": Decimal("132000.00"),
        "portas": 4,
        "placa": "AAA1A19",
        "renavam": "00000000019",
        "status": "Disponível",
    },
    {
        "nome": "Renegade Sport",
        "marca": "Jeep",
        "modelo": "Renegade",
        "ano_fabricacao": 2018,
        "ano_modelo": 2018,
        "tipo": "SUV",
        "descricao": "Robusto para uso urbano e estrada",
        "cor": "Verde",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.8",
        "potencia": "130 hp",
        "quilometragem": 72000,
        "preco": Decimal("98000.00"),
        "portas": 4,
        "placa": "AAA1A20",
        "renavam": "00000000020",
        "status": "Disponível",
    },
]


def run():
    """Insere os carros no banco. Use com cuidado."""
    # cria tabelas se necessário
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        for c in CARROS:
            carro = Carro(**c)
            db.add(carro)
        db.commit()
        print(f"Inseridos {len(CARROS)} carros com sucesso.")
    except Exception as e:
        db.rollback()
        print("Erro ao inserir dados:", e)
    finally:
        db.close()


if __name__ == "__main__":
    run()
